### ISSUE TITLE
Filter to specific apps on sharing media

### ISSUE THREAD

**Issue by canberkozcelik** [yvzzztrk/mposter-android#10] opened 2016-01-05 07:08 UTC
There are lots of apps not being used by most of our target user type, on sharing media we're showing them too.

Acceptance Criteria:
Only most common social media and communication apps should be showed on sharing

**Comment by canberkozcelik** [comment] 2016-01-05 07:43
http://stackoverflow.com/a/18068122

**Comment by yvzzztrk** [comment] 2016-01-05 08:15
this is unprofessional. let user to share with any app they want. I suggest, this issue is not a bug. This is enchaemnmht. Close or Change pls

**Comment by canberkozcelik** [comment] 2016-01-05 08:33
because share intent shows nonsense apps on sharing screen (maps, evernote, calendar, etc.), nonetheless it should count as bug and the apps that will allowed should be choose @yvzzztrk

**Comment by yvzzztrk** [comment] 2016-01-05 08:40
Try twitter app, share twit and you will see apps that can not even share a twit.

**Comment by canberkozcelik** [comment] 2016-01-05 09:03
We can notify twitter about that, but for our case we should filter the apps that out of sharing description

**Comment by yvzzztrk** [comment] 2016-01-05 11:53
We should not concern about this. This problem only concerns apps that allows sharing content which unrecognized by them. I STRONGLY RECOMMEND to close this issue.

**Comment by yvzzztrk** [comment] 2016-01-05 13:39
i win.

**Closed** 2016-01-05 13:39 UTC
Labels: bug, wontfix
